[build]
  functions = "netlify-functions"
  publish = "dist"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/scrape"
  to = "/.netlify/functions/scrape"
  status = 200

[[redirects]]
  from = "/api/generate-idea"
  to = "/.netlify/functions/generate-idea"
  status = 200
