import {
  Users,
  Rocket,
  Lightbulb,
  Cpu,
  Code,
  Zap,
  TrendingUp,
  Clock,
  Globe,
  Building2,
  Target,
  BookOpen,
  Crown,
  Monitor,
  BarChart3,
} from "lucide-react";

export const communityIcons = {
  "r/SaaS": Users,
  "r/startups": Rocket,
  "r/Entrepreneur": Lightbulb,
  "r/technology": Cpu,
  "r/sideproject": Code,
  "r/indiehackers": Zap,
  "r/growthhacking": TrendingUp,
  "r/Productivity": Clock,
  "r/InternetIsBeautiful": Globe,
  "r/TechStartup": Building2,
  "r/askmarketing": Target,
  "r/learnprogramming": BookOpen,
  "r/founders": Crown,
  "r/tech": Monitor,
  "r/digitalmarketing": BarChart3,
};
